"""
Fetch a hero image for each city in locations/[slug]/data.ts from Pexels.

Saves images to web/public/locations/[slug].jpg and appends a heroImage
field to each CityData entry in the data.ts file.

Strategy:
  - For each city, search Pexels for "[city name] city / skyline / landmark"
  - Pick the first orientation:landscape result with decent size
  - Save photographer credit for attribution

Pexels licence allows free commercial use without attribution; we attach
photographer credit anyway as good practice.

Run:
    python pipeline/fetch_city_images.py             # fetch for all 30
    python pipeline/fetch_city_images.py --only bradford
    python pipeline/fetch_city_images.py --skip-existing  # don't refetch if file exists
"""
import argparse
import json
import os
import re
import sys
import time
from pathlib import Path

import httpx

ROOT = Path(__file__).resolve().parents[1]
DATA_TS = ROOT / "web" / "src" / "app" / "locations" / "[slug]" / "data.ts"
OUT_DIR = ROOT / "web" / "public" / "locations"

try:
    from dotenv import load_dotenv
    load_dotenv(Path(__file__).resolve().parents[2] / ".env", override=True)
except ImportError:
    pass

PEXELS_KEY = os.getenv("PEXELS_API_KEY")


# City -> search query overrides for cities where the plain name returns
# ambiguous results (e.g. "Reading" returns books).
QUERY_OVERRIDES = {
    "reading": "reading berkshire town",
    "york": "york england minster",
    "newcastle": "newcastle upon tyne quayside",
    "cambridge": "cambridge england university",
    "oxford": "oxford england spires",
    "hull": "hull east yorkshire marina",
    "brighton": "brighton seafront pier",
    "bournemouth": "bournemouth beach",
    "plymouth": "plymouth devon harbour",
    "portsmouth": "portsmouth spinnaker tower",
    "stoke-on-trent": "stoke on trent staffordshire",
    "milton-keynes": "milton keynes uk centre",
}


def pexels_search(query: str, per_page: int = 5) -> list[dict]:
    if not PEXELS_KEY:
        raise RuntimeError("PEXELS_API_KEY not set")
    r = httpx.get(
        "https://api.pexels.com/v1/search",
        headers={"Authorization": PEXELS_KEY},
        params={
            "query": query,
            "per_page": per_page,
            "orientation": "landscape",
            "size": "large",
        },
        timeout=20.0,
    )
    r.raise_for_status()
    return r.json().get("photos", [])


def download(url: str, dest: Path) -> int:
    r = httpx.get(url, timeout=30.0)
    r.raise_for_status()
    dest.parent.mkdir(parents=True, exist_ok=True)
    dest.write_bytes(r.content)
    return len(r.content)


def fetch_for_city(slug: str, name: str, skip_existing: bool) -> dict | None:
    out_path = OUT_DIR / f"{slug}.jpg"
    if skip_existing and out_path.exists():
        print(f"  [{slug}]  exists, skipping")
        return None

    query = QUERY_OVERRIDES.get(slug, f"{name} city uk")
    photos = pexels_search(query, per_page=5)
    if not photos:
        # Fallback: try shorter
        photos = pexels_search(name, per_page=5)
    if not photos:
        print(f"  [{slug}]  no photos found for query {query!r}")
        return None

    # Pick the first landscape, large-enough photo (Pexels returns landscape
    # already, but we double-check dimensions).
    pick = None
    for p in photos:
        w = p.get("width", 0)
        h = p.get("height", 0)
        if w >= 1200 and w >= h:
            pick = p
            break
    if pick is None:
        pick = photos[0]

    src_url = pick["src"]["landscape"] or pick["src"]["large2x"] or pick["src"]["original"]
    download(src_url, out_path)

    return {
        "public_url": f"/locations/{slug}.jpg",
        "photographer": pick.get("photographer", ""),
        "photographer_url": pick.get("photographer_url", ""),
        "pexels_url": pick.get("url", ""),
        "alt": pick.get("alt", f"{name} city scene"),
    }


def parse_existing_data_ts(text: str) -> tuple[str, str, dict[str, dict]]:
    """Crude but workable: return (type_block, prelude, cities_text_by_slug).
    We do NOT parse the body objects — we just re-emit them with an injected
    heroImage field. The data.ts file is generated by us so format is stable."""
    # Find each city block by scanning for `"slug": "xxxx"` openings
    return text  # placeholder; not used in append mode


def update_data_ts_with_hero_images(hero_map: dict[str, dict]) -> int:
    """Patch data.ts so that each CityData entry gains a `heroImage` field
    plus the type adds it. Idempotent: re-running replaces previous values."""
    text = DATA_TS.read_text(encoding="utf-8")

    # 1. Ensure the CityData type declares heroImage. If already present, leave.
    if "heroImage:" not in text.split("export const CITIES")[0]:
        # Inject before the closing brace of `CityData` type. Locate the
        # `adjacentTown: { slug: string; name: string };` line and add after it.
        text = re.sub(
            r"(adjacentTown: \{ slug: string; name: string \};\s*\n)",
            r"\1  heroImage: {\n    url: string;\n    alt: string;\n    photographer: string;\n    photographer_url: string;\n    pexels_url: string;\n  };\n",
            text,
            count=1,
        )

    # 2. For each city, append a heroImage block before the closing `},` of its
    #    entry. Use the unique `"slug": "xxxx"` opening to find the block,
    #    then scan forward to the next `},\n` at the top object level.
    updated = 0
    for slug, hero in hero_map.items():
        if not hero:
            continue
        # Drop any existing heroImage line for this city first (idempotent)
        pattern_existing = re.compile(
            r'(  "' + re.escape(slug) + r'":\s*\{[\s\S]*?)\n    heroImage:\s*\{[\s\S]*?\},\n', re.MULTILINE
        )
        text = pattern_existing.sub(r"\1\n", text)

        # Find the city's adjacentTown line and inject heroImage immediately after it
        city_pattern = re.compile(
            r'(  "' + re.escape(slug) + r'":\s*\{[\s\S]*?adjacentTown:\s*\{[^}]*\},\n)', re.MULTILINE
        )

        def replace_in_city(m: re.Match) -> str:
            block = m.group(1)
            hero_lines = (
                "    heroImage: {\n"
                f"      url: {json.dumps(hero['public_url'])},\n"
                f"      alt: {json.dumps(hero['alt'])},\n"
                f"      photographer: {json.dumps(hero['photographer'])},\n"
                f"      photographer_url: {json.dumps(hero['photographer_url'])},\n"
                f"      pexels_url: {json.dumps(hero['pexels_url'])},\n"
                "    },\n"
            )
            return block + hero_lines

        new_text, n = city_pattern.subn(replace_in_city, text, count=1)
        if n > 0:
            text = new_text
            updated += 1
        else:
            print(f"  WARN: could not patch heroImage into '{slug}' (city block not found)")

    DATA_TS.write_text(text, encoding="utf-8")
    return updated


def load_city_list_from_data() -> list[tuple[str, str]]:
    """Read data.ts to find (slug, name) pairs."""
    text = DATA_TS.read_text(encoding="utf-8")
    pairs = re.findall(r'"(\w[\w-]*)":\s*\{\s*\n\s*slug:\s*"([\w-]+)",\s*\n\s*name:\s*"([^"]+)"', text)
    out = []
    for outer, slug, name in pairs:
        if outer == slug:
            out.append((slug, name))
    return out


def main():
    parser = argparse.ArgumentParser()
    parser.add_argument("--only", help="fetch one specific slug")
    parser.add_argument("--skip-existing", action="store_true", help="don't refetch if file exists")
    parser.add_argument("--sleep", type=float, default=0.3, help="seconds between requests")
    args = parser.parse_args()

    if not PEXELS_KEY:
        sys.exit("PEXELS_API_KEY not set in .env")

    cities = load_city_list_from_data()
    if args.only:
        cities = [(s, n) for s, n in cities if s == args.only]

    print(f"Fetching hero images for {len(cities)} cities...")
    print()

    hero_map: dict[str, dict] = {}
    OUT_DIR.mkdir(parents=True, exist_ok=True)
    for slug, name in cities:
        try:
            h = fetch_for_city(slug, name, args.skip_existing)
            if h:
                hero_map[slug] = h
                print(f"  [{slug:>16}]  ok  -> {h['public_url']}  ({h['photographer']})")
            time.sleep(args.sleep)
        except Exception as e:
            print(f"  [{slug:>16}]  ERROR {type(e).__name__}: {e}")

    if hero_map:
        print()
        print(f"Patching {len(hero_map)} heroImage entries into {DATA_TS.name}...")
        n = update_data_ts_with_hero_images(hero_map)
        print(f"  {n} entries patched")
    else:
        print("\nNo new images fetched; data.ts left as-is.")


if __name__ == "__main__":
    main()
