"""
Rewrite glossary body content from agency-founder framing to generalist
UK business owner framing.

Reads web/src/app/glossary/[slug]/data.ts, parses each entry, sends each
body to DeepSeek with a strict rewrite prompt, writes the file back with
the same structure preserved (slug, term, category, primary_kw unchanged).

Anti-cannibalisation: structural changes are forbidden. Only the body
content is rewritten. Length kept close to original (+/-15%).

Run:
    python pipeline/rewrite_glossary.py                # all 52
    python pipeline/rewrite_glossary.py --only badr
    python pipeline/rewrite_glossary.py --limit 3      # smoke test
    python pipeline/rewrite_glossary.py --workers 4
"""
import argparse
import os
import re
import sys
import time
from concurrent.futures import ThreadPoolExecutor, as_completed
from pathlib import Path

sys.path.insert(0, os.path.dirname(__file__))
sys.path.insert(0, os.path.join(os.path.dirname(__file__), "..", ".."))
sys.path.insert(0, os.path.join(os.path.dirname(__file__), "..", "..", "agents", "utils"))

try:
    from dotenv import load_dotenv
    load_dotenv(Path(__file__).resolve().parents[2] / ".env", override=True)
except ImportError:
    pass

from config_supabase import DEEPSEEK_API_KEY
from deepseek_client import DeepSeekClient


ROOT = Path(__file__).resolve().parents[1]
DATA_TS = ROOT / "web" / "src" / "app" / "glossary" / "[slug]" / "data.ts"


SYSTEM_PROMPT = """You are a senior ICAEW-qualified UK accountant rewriting glossary entries for Holloway Davies, a generalist UK accountancy firm.

Audience: UK business owners. Limited company directors, contractors working through their own Ltd, sole traders, freelancers, partnership owners, and small business owners across every sector. NOT agency founders specifically.

Your job: take an existing HTML glossary entry and rewrite the body to remove all "agency founder" / "your agency" framing while preserving:
  - All factual accuracy (rates, thresholds, dates, HMRC form names)
  - The HTML structure (<p>, <ul>, <li>, <strong>)
  - Roughly the same length (do NOT shorten by more than 15%)
  - The same conceptual coverage and depth

VOICE: Financial Times editorial. Precise, confident, plain English, occasional sharp opinion. Use UK English (specialise, organise, recognise).

BANS:
- NO em-dashes anywhere. Use commas, full stops, parentheses, middle dots.
- NO "agency founder" / "agency founders" / "for agency founders" / "your agency" framing.
- "Agency" as a noun in a sector list ("a marketing agency", "an advertising agency") is fine. The ban is on the AUDIENCE framing.
- Replace agency-specific examples with generalist UK business examples: limited company directors, contractors, sole traders, food manufacturers, software companies, consultancies, retailers, partnerships, etc.
- Keep the "When this matters" or similar closing block but reframe it for UK business owners not agency founders.

OUTPUT: only the new HTML body. No JSON wrapper, no markdown fences, no commentary. The body must start with <p> and end with </p>.
"""


def call_deepseek(client: DeepSeekClient, entry: dict) -> str:
    user_prompt = f"""Term: {entry['term']}
Category: {entry['category']}
Primary keyword: {entry['primary_kw']}

Existing body (HTML):
{entry['body']}

Rewrite the body. Return ONLY the new HTML, starting with <p> and ending with </p>."""
    raw = client.generate_creative(
        prompt=user_prompt,
        system=SYSTEM_PROMPT,
        temperature=0.55,
        max_tokens=2400,
    )
    # Strip any accidental code fences
    raw = re.sub(r"^```(?:html)?\s*", "", raw.strip())
    raw = re.sub(r"\s*```$", "", raw.strip())
    return raw.strip()


# Banned strings in OUTPUT
OUTPUT_BANNED = (
    "—",
    "agency founder",
    "agency founders",
    "for agency founders",
    "your agency",
)


def validate_body(slug: str, original: str, new: str) -> tuple[bool, str]:
    if not new.lstrip().startswith("<p>"):
        return False, "doesn't start with <p>"
    low = new.lower()
    for b in OUTPUT_BANNED:
        if b.lower() in low:
            return False, f"banned string: {b!r}"
    # Length floor: at least 60% of original
    if len(new) < 0.6 * len(original):
        return False, f"too short: {len(new)} vs original {len(original)}"
    return True, ""


# Regex to extract each glossary entry from data.ts. The file format is
# stable (auto-generated by generate_glossary.py originally).
ENTRY_PATTERN = re.compile(
    r'  "([^"]+)":\s*\{\s*\n'
    r'\s*slug:\s*"([^"]+)",\s*\n'
    r'\s*term:\s*"([^"]+)",\s*\n'
    r'\s*category:\s*"([^"]+)",\s*\n'
    r'\s*primary_kw:\s*"([^"]+)",\s*\n'
    r'\s*body:\s*`([^`]*)`,\s*\n'
    r'\s*\},',
    re.MULTILINE,
)


def load_entries() -> list[dict]:
    text = DATA_TS.read_text(encoding="utf-8")
    out = []
    for m in ENTRY_PATTERN.finditer(text):
        outer, slug, term, category, primary_kw, body = m.groups()
        if outer != slug:
            continue
        out.append({
            "slug": slug,
            "term": term,
            "category": category,
            "primary_kw": primary_kw,
            "body": body,
            "span": (m.start(), m.end()),
        })
    return out


def emit_entry(slug: str, term: str, category: str, primary_kw: str, body: str) -> str:
    """Re-emit a single glossary entry block. body is raw HTML; we wrap in
    backticks (template literal). Escape any backticks in the body."""
    safe_body = body.replace("`", "\\`").replace("${", "\\${")
    # Escape double quotes in the term/category strings if present
    return (
        f'  "{slug}": {{\n'
        f'    slug: "{slug}",\n'
        f'    term: "{term.replace(chr(34), chr(92)+chr(34))}",\n'
        f'    category: "{category}",\n'
        f'    primary_kw: "{primary_kw.replace(chr(34), chr(92)+chr(34))}",\n'
        f'    body: `{safe_body}`,\n'
        f'  }},'
    )


def rewrite_one(entry: dict) -> str | None:
    client = DeepSeekClient(api_key=DEEPSEEK_API_KEY)
    slug = entry["slug"]
    t0 = time.time()
    for attempt in range(1, 4):
        try:
            new_body = call_deepseek(client, entry)
        except Exception as e:
            print(f"  [{slug:>32}]  DeepSeek error: {e}")
            continue
        ok, msg = validate_body(slug, entry["body"], new_body)
        if ok:
            elapsed = time.time() - t0
            print(f"  [{slug:>32}]  {elapsed:>5.1f}s  OK  ({len(entry['body'])} -> {len(new_body)} chars)")
            return new_body
        print(f"  [{slug:>32}]  attempt {attempt}: {msg}")
    print(f"  [{slug:>32}]  GAVE UP after 3 attempts")
    return None


def main():
    parser = argparse.ArgumentParser()
    parser.add_argument("--only", help="rewrite one slug only")
    parser.add_argument("--limit", type=int, help="rewrite first N entries")
    parser.add_argument("--workers", type=int, default=4)
    parser.add_argument("--dry-run", action="store_true")
    args = parser.parse_args()

    entries = load_entries()
    print(f"Parsed {len(entries)} glossary entries from {DATA_TS.name}")

    targets = entries
    if args.only:
        targets = [e for e in entries if e["slug"] == args.only]
        if not targets:
            sys.exit(f"slug not found: {args.only}")
    elif args.limit:
        targets = entries[: args.limit]

    print(f"Rewriting {len(targets)} entries (workers={args.workers})...")
    print()

    new_bodies: dict[str, str] = {}
    with ThreadPoolExecutor(max_workers=args.workers) as pool:
        futures = {pool.submit(rewrite_one, e): e for e in targets}
        for fut in as_completed(futures):
            e = futures[fut]
            nb = fut.result()
            if nb is not None:
                new_bodies[e["slug"]] = nb

    print()
    print(f"Successful rewrites: {len(new_bodies)} / {len(targets)}")
    if not new_bodies:
        sys.exit("no rewrites; nothing to write")

    if args.dry_run:
        print("\n[dry-run] First entry rewritten body preview:")
        first = list(new_bodies.keys())[0]
        print(f"--- {first} ---")
        print(new_bodies[first][:600])
        return

    # Reassemble the file. We replace each entry's body in-place by reading
    # the file fresh and patching each entry's body block.
    text = DATA_TS.read_text(encoding="utf-8")
    patched = 0
    for slug, new_body in new_bodies.items():
        safe = new_body.replace("\\", "\\\\").replace("`", "\\`").replace("${", "\\${")
        # Find this entry's body assignment and replace just the body content
        entry_pattern = re.compile(
            r'(  "' + re.escape(slug) + r'":\s*\{\s*\n'
            r'\s*slug:\s*"' + re.escape(slug) + r'",\s*\n'
            r'\s*term:\s*"[^"]*",\s*\n'
            r'\s*category:\s*"[^"]*",\s*\n'
            r'\s*primary_kw:\s*"[^"]*",\s*\n'
            r'\s*body:\s*)`[^`]*`(,\s*\n\s*\},)',
            re.MULTILINE,
        )
        new_text, n = entry_pattern.subn(
            lambda m: m.group(1) + "`" + safe + "`" + m.group(2),
            text,
            count=1,
        )
        if n == 1:
            text = new_text
            patched += 1
        else:
            print(f"  WARN: couldn't patch {slug}")

    DATA_TS.write_text(text, encoding="utf-8")
    print(f"\nPatched {patched} entries in {DATA_TS.name}")


if __name__ == "__main__":
    main()
