// AUTO-GENERATED by pipeline/generate_glossary.py
// Edit definitions in this file; do not regenerate without backing up changes.

export type GlossaryEntry = {
  slug: string;
  term: string;
  category: string;
  primary_kw: string;
  body: string;
};

export const GLOSSARY: Record<string, GlossaryEntry> = {
  "badr": {
    slug: "badr",
    term: "BADR (Business Asset Disposal Relief)",
    category: "Tax",
    primary_kw: "what is BADR",
    body: `<p>Business Asset Disposal Relief (BADR) is a UK tax relief that reduces the capital gains tax you pay when you sell or dispose of your business, applying a lower rate of 14% on qualifying gains up to a lifetime limit of £1 million.</p>

<p>For business owners, BADR is the most valuable tax relief available when exiting a company. It applies when you sell shares in your personal trading company or sell the business's assets as a sole trader. To qualify, you must have owned the business and been an employee or officer for at least two years before the sale. The relief reduces the capital gains tax rate from the standard 20% (for higher-rate taxpayers) to just 14% in the 2025/26 tax year, saving you 6p for every £1 of profit above your annual exempt amount.</p>

<p>However, the rules are tightening. From 6 April 2026, the BADR rate rises to 18%, so if you are planning an exit, the 2025/26 tax year offers the lowest rate. The lifetime limit of £1 million of qualifying gains has been fixed since March 2020 and is not indexed for inflation, meaning a £1 million gain in 2025 buys far less real value than it did five years ago.</p>

<p>To claim BADR, you must ensure your company shares meet the "personal company" conditions: you must hold at least 5% of the ordinary share capital and voting rights, and be entitled to at least 5% of the distributable profits and assets on a winding up. Many business owners trip up by holding shares through a separate holding company or by having non-voting shares that fail the 5% test. You should also watch the "significant commercial interdependence" rule if you run multiple companies through separate entities.</p>

<p>BADR applies to disposals of the whole business, not partial sales of shares over time. If you sell your company in stages, only the final disposal that transfers control qualifies. You can also claim BADR on goodwill and certain business assets if you sell as a sole trader, but note that goodwill disposals to a company you control are specifically excluded.</p>

<p>When this matters for UK business owners: If you are planning to sell your limited company or sole trader business, BADR is your single biggest tax-saving tool, potentially saving tens of thousands of pounds compared to paying full capital gains tax. With the rate rising to 18% in April 2026, now is the time to structure your exit to qualify.</p>`,
  },
  "ir35": {
    slug: "ir35",
    term: "IR35 (Off-Payroll Working Rules)",
    category: "Contractors",
    primary_kw: "what is IR35",
    body: `<p>IR35, also known as the off-payroll working rules, is a set of tax legislation designed to prevent contractors who work like employees from paying less tax and National Insurance by operating through a limited company.</p>

<p>For UK businesses engaging contractors, IR35 determines whether those contractors must be treated as employees for tax purposes, even though they invoice through their own personal service company (PSC). If a contract falls inside IR35, the fee-payer (which could be your business or an agency in the chain) becomes responsible for deducting income tax and National Insurance from the contractor's fees, just as you would for a permanent employee. This removes the contractor's ability to take dividends and pay lower tax rates.</p>

<p>The rules apply differently depending on the size of the end client. For medium and large clients (meeting at least two of: turnover over £10.2m, balance sheet over £5.1m, or over 50 employees), the client must determine the contractor's status and pass that determination down the chain. For small clients, the responsibility stays with the contractor's PSC. If you are the fee-payer, you must operate payroll deductions if the client tells you the role is inside IR35.</p>

<p>Key financial implications include:</p>
<ul>
<li>You must deduct PAYE income tax and employee National Insurance (12% on earnings between £12,570 and £50,270 for 2025/26) from the contractor's fees</li>
<li>You must pay employer National Insurance (15% on earnings above £9,100 for 2025/26) and apprenticeship levy (0.5% on pay bills over £3m)</li>
<li>The contractor loses access to dividend tax rates (8.75% basic rate, 33.75% higher rate) and the £500 dividend allowance</li>
<li>You must provide a status determination statement to the contractor and the next party in the chain</li>
</ul>
<p>If you get the determination wrong, HMRC can pursue you for unpaid tax, interest, and penalties. The contractor cannot claim travel and subsistence expenses against inside-IR35 engagements either.</p>

<p>When this matters for UK business owners: IR35 directly affects your contractor margins, your payroll administration burden, and your risk exposure. You must have a robust process for receiving and acting on status determinations, and you should consider indemnity clauses in your contracts with end clients to protect your business if they provide incorrect determinations.</p>`,
  },
  "mtd-itsa": {
    slug: "mtd-itsa",
    term: "MTD ITSA (Making Tax Digital for Income Tax)",
    category: "Compliance",
    primary_kw: "what is MTD ITSA",
    body: `<p>Making Tax Digital for Income Tax (MTD ITSA) is a government initiative requiring sole traders and landlords to keep digital records and submit quarterly updates to HMRC using compatible software, rather than filing a single annual Self Assessment tax return.</p>

<p>For UK business owners, MTD ITSA fundamentally changes how you report your business income to HMRC. If your business is structured as a sole trader or partnership (not a limited company), and your gross income from self-employment and property exceeds £50,000 per year, you must comply from April 2026. If your income is between £30,000 and £50,000, compliance starts from April 2027. Those with income below £30,000 can voluntarily opt in, but are not required to.</p>

<p>Under MTD ITSA, you must use HMRC-recognised software to record all business income and expenses digitally. You then submit quarterly summaries of your income and expenses to HMRC within one month of each quarter end (typically 5 August, 5 November, 5 February, and 5 May). At the end of the year, you submit a final declaration to confirm your figures, and any tax owed is calculated based on your total annual profit.</p>

<p>Key practical points for UK business owners:</p>

<ul>
<li><strong>Software costs:</strong> You will need to budget for MTD-compatible accounting software, such as Xero, FreeAgent, or QuickBooks. Many have monthly subscription fees starting around £10-£30 per month.</li>
<li><strong>No more spreadsheets:</strong> Simple Excel or paper records are no longer acceptable for MTD ITSA compliance. You must use software that connects directly to HMRC's API.</li>
<li><strong>Quarterly deadlines:</strong> You must submit four updates per year, plus a final declaration. Missing these deadlines can result in late filing penalties.</li>
<li><strong>Corporation tax exemption:</strong> If your business is a limited company, MTD ITSA does not apply to you yet. However, MTD for Corporation Tax is expected from 2026, so you should prepare your digital record-keeping now.</li>
<li><strong>VAT overlap:</strong> If your business is already registered for VAT and using MTD for VAT, you can use the same software for both, simplifying your accounting.</li>
</ul>

<p>When this matters for UK business owners: If you operate as a sole trader or partnership with gross income over £50,000, you must start preparing for MTD ITSA now. Choose compatible software, set up quarterly reminders, and consider working with an accountant familiar with digital reporting to avoid penalties and stay compliant from April 2026.</p>`,
  },
  "mtd": {
    slug: "mtd",
    term: "MTD (Making Tax Digital)",
    category: "Compliance",
    primary_kw: "what is MTD",
    body: `<p>Making Tax Digital (MTD) is a UK government initiative that requires businesses to keep digital records and submit tax returns using compatible software, rather than paper-based or manual spreadsheets. For UK business owners, MTD fundamentally changes how you record income, expenses, and file your quarterly VAT returns, with an eventual extension to income tax self-assessment.</p>

<p>MTD for VAT has been mandatory since April 2019 for businesses with a taxable turnover above the VAT threshold (currently £90,000 from April 2024). If your business's VAT-taxable turnover exceeds this figure, you must use MTD-compatible software to submit your VAT returns directly to HMRC. This means no more logging into the HMRC website to manually enter figures. Instead, your accounting software (such as Xero, QuickBooks, or FreeAgent) must be MTD-compatible and will send the data automatically. Even if your turnover is below the threshold, you can voluntarily join MTD, which some limited company directors and sole traders do to streamline their bookkeeping.</p>

<p>The key practical requirement is that you must maintain digital records of all transactions, including sales, purchases, and VAT amounts. You cannot use paper records or non-digital spreadsheets without bridging software. For most businesses, this typically means using cloud accounting software that tracks every invoice and expense in real time. The software calculates your VAT liability and submits the return quarterly, with a final annual submission.</p>

<p>From April 2026, MTD will expand to income tax self-assessment for sole traders and landlords with income over £50,000. For sole traders, this will mean quarterly digital updates to HMRC for your income and expenses, rather than a single annual tax return. Partnerships and limited company directors are not yet in scope for MTD for income tax, but the government plans to extend it in future years.</p>

<p>For business owners, the main benefits include fewer manual errors, automatic VAT calculations, and a clearer real-time picture of your cash flow. The main cost is the subscription fee for MTD-compatible software, typically £10-£30 per month. You can use bridging software to connect spreadsheets to HMRC, but most businesses find cloud accounting software more efficient.</p>

<p><strong>When this matters for UK business owners</strong>: MTD affects you immediately if your VAT-taxable turnover exceeds £90,000, as you must use compatible software for VAT returns. If you are a sole trader, prepare for MTD for income tax from April 2026 if your income exceeds £50,000. Even below these thresholds, adopting MTD-compatible software early can save time and reduce errors as your business grows.</p>`,
  },
  "section-455": {
    slug: "section-455",
    term: "Section 455 (Director's Loan Tax Charge)",
    category: "Tax",
    primary_kw: "what is Section 455",
    body: `<p>Section 455 is a tax charge that applies when a close company (typically a small owner-managed business) makes a loan to a director or shareholder that is not repaid within nine months of the end of the accounting period.</p>

<p>This charge acts as a deterrent against extracting money from a company as a director's loan rather than through salary or dividends. If a director borrows money from their company and does not repay it within the nine-month window, the company must pay a tax charge equal to 33.75% of the loan amount (the rate for 2025/26). This charge is not a penalty but a deposit: it is refunded to the company once the loan is repaid, provided the repayment happens after the nine-month deadline.</p>

<p>Here is how it works in practice for UK business owners:</p>

<ul>
<li><strong>Loan creation:</strong> If your company lends you £20,000 on 1 January 2025, and you have not repaid it by 30 September 2025 (nine months after the end of the accounting period if your year-end is 31 December), the company must pay £6,750 in Section 455 tax (33.75% of £20,000) by the corporation tax filing deadline.</li>
<li><strong>Repayment and refund:</strong> If you repay the loan on 1 March 2026, the company can reclaim the £6,750 from HMRC. The refund is processed as a reduction in the company's corporation tax liability for the period in which the repayment occurs.</li>
<li><strong>Interest implications:</strong> If the loan is not repaid within the nine-month window, HMRC also charges interest on the unpaid Section 455 tax from the original due date until the date of repayment.</li>
<li><strong>Exceptions:</strong> Loans of £15,000 or less to a director who works full-time for the company (and does not own more than 5% of the shares) are exempt from Section 455. Similarly, loans made in the ordinary course of business (e.g., a credit account for expenses) are not caught.</li>
</ul>

<p>Section 455 applies regardless of whether the loan is formally documented or simply an overdrawn director's loan account. HMRC treats any amount owed by a director to the company as a loan, including unpaid dividends or salary that have been credited to the director's account but not withdrawn.</p>

<p><strong>When this matters for UK business owners</strong></p>

<p>This matters for limited company directors and other business owners because taking a director's loan without planning the repayment timeline can trigger an unexpected 33.75% tax charge on the company's cash flow, plus interest. Always structure withdrawals as salary or dividends where possible, or ensure any loan is repaid within nine months of your year-end to avoid the charge entirely.</p>`,
  },
  "aia": {
    slug: "aia",
    term: "AIA (Annual Investment Allowance)",
    category: "Tax",
    primary_kw: "what is AIA",
    body: `<p>The Annual Investment Allowance (AIA) is a UK tax relief that lets you deduct the full cost of qualifying plant and machinery from your taxable profits in the year you buy it, rather than spreading the deduction over several years.</p>
<p>For UK business owners, the AIA is a powerful tool for reducing corporation tax. If your company buys equipment like computers, servers, office furniture, software, or even certain fixtures in a leased office, you can claim the full cost against your profits immediately. For the 2025/26 tax year, the AIA limit is £1 million, meaning you can deduct up to £1 million of qualifying capital expenditure in a single accounting period. This is particularly valuable if your business has a high taxable profit and you need to invest in technology or infrastructure to scale.</p>
<p>To claim the AIA, you must be a sole trader, a partnership, or a limited company. The relief applies to most plant and machinery, but not to cars, buildings, or assets used for leasing. For most businesses, typical qualifying items include:</p>
<ul>
<li>Laptops, monitors, and other IT hardware</li>
<li>Office furniture and fixtures</li>
<li>Software licences (if bought outright, not as a subscription)</li>
<li>Certain building improvements like air conditioning or security systems</li>
</ul>
<p>The AIA works alongside other capital allowances. If you spend more than £1 million in a year, the excess goes into the main pool and attracts writing-down allowances at 18% per year. If your business is small and pays corporation tax at the small profits rate of 19%, claiming the AIA effectively saves you 19p in tax for every £1 spent. For larger companies paying the main rate of 25%, the saving is 25p per £1.</p>
<p>One practical point: the AIA is time-sensitive. You must claim it in the accounting period when you incur the expenditure. If your company's year-end is 31 March 2026 and you buy equipment in February 2026, you can claim the AIA in that year's return. But if you delay the purchase to April 2026, it falls into the next period.</p>
<p>When this matters for UK business owners: when you are planning significant capital purchases such as a full office fit-out, a fleet of high-spec computers for a growing team, or upgrading your server infrastructure, the AIA lets you front-load the tax relief, reducing your corporation tax bill in the year of investment and freeing up cash flow for growth.</p>`,
  },
  "r-and-d-tax-credits": {
    slug: "r-and-d-tax-credits",
    term: "R&D Tax Credits",
    category: "Tax",
    primary_kw: "what are R&D tax credits",
    body: `<p>R&D tax credits are a government relief that reduces your company's corporation tax bill or provides a cash payment for spending on research and development in science or technology.</p>

<p>For UK limited companies, R&D tax credits apply when your business develops new software, tools, or processes that resolve scientific or technological uncertainty. This is not limited to dedicated tech firms. If your consultancy builds custom software for clients, your manufacturing business automates production workflows, or your retailer creates proprietary logistics platforms, you may qualify. The key test is whether your project advances knowledge in a field of science or technology, not whether it succeeds commercially.</p>

<p>There are two schemes. The <strong>RDEC (Research and Development Expenditure Credit)</strong> scheme is for large companies, but most SMEs use the <strong>SME R&D Relief</strong> scheme if they have fewer than 500 employees and turnover under €100 million. Under the SME scheme, you can claim up to 86% of your qualifying R&D costs as an enhanced deduction. For example, if you spend £100,000 on qualifying costs, you can deduct £186,000 from your taxable profits. If your company is loss-making, you can surrender the loss for a cash payment worth up to 14.5% of the qualifying costs.</p>

<p>Qualifying costs include staff salaries, employer's National Insurance, pension contributions, software licences, cloud computing costs, and subcontractor fees (subject to restrictions). For 2025/26, the rates are unchanged from the previous year. The SME payable credit rate remains 14.5% for loss-making companies, and the RDEC rate is 20% (with a 15% net benefit after tax).</p>

<p>Common qualifying activities include building a bespoke customer management system, developing a proprietary data analytics dashboard, creating automated inventory or reporting tools, or integrating AI into product development where the outcome is uncertain. Routine website builds using existing templates or standard off-the-shelf software implementations do not qualify.</p>

<p>Claims must be submitted within two years of the end of your accounting period. HMRC has increased scrutiny of R&D claims, so you need clear technical narratives and supporting evidence. Since 2024, all claims must be made digitally and include a breakdown of qualifying costs.</p>

<p><strong>When this matters for UK business owners</strong>: If your company invests in developing new software, tools, or processes that push technical boundaries, R&D tax credits can return significant cash to your business or reduce your tax bill. This is especially valuable for businesses reinvesting profits into innovation, as the relief directly supports growth without diluting equity.</p>`,
  },
  "corporation-tax": {
    slug: "corporation-tax",
    term: "Corporation Tax",
    category: "Tax",
    primary_kw: "UK corporation tax explained",
    body: `<p>Corporation tax is the tax that UK limited companies pay on their profits, including income from trading, investments, and selling assets for more than they cost. For business owners operating through a limited company, this is the primary tax you pay on your retained profits after deducting salaries, dividends, and other allowable business expenses.</p>

<p>From 1 April 2025 to 5 April 2026, the UK corporation tax system uses a marginal relief structure. If your company's annual profits are £50,000 or less, you pay the small profits rate of 19%. If profits exceed £250,000, you pay the main rate of 25%. Between £50,000 and £250,000, marginal relief gradually increases your effective rate from 19% to 25%. For example, a consultancy with £100,000 profit pays roughly 22.5% after marginal relief, not a flat 25%.</p>

<p>Key points for UK business owners:</p>
<ul>
<li><strong>Payment timing:</strong> Corporation tax is due nine months and one day after your accounting period ends. For a 31 March year end, payment is due by 1 January the following year.</li>
<li><strong>Quarterly instalments:</strong> If your annual corporation tax liability exceeds £10,000 (typically profits over £1.5 million), you must pay in quarterly instalments. Most small limited companies and contractors won't trigger this.</li>
<li><strong>Allowable deductions:</strong> You can deduct salaries, pension contributions, rent, equipment, software subscriptions, professional fees, and marketing costs. Dividends paid to shareholders are not deductible.</li>
<li><strong>Capital allowances:</strong> The Annual Investment Allowance (AIA) remains at £1 million for 2025/26, letting you claim 100% relief on most plant and machinery purchases, including computers and office equipment.</li>
<li><strong>Research and Development (R&D):</strong> If your business develops software, tools, or new processes, you may qualify for R&D tax credits, which can reduce your corporation tax bill or generate a cash repayment.</li>
</ul>
<p>When this matters for UK business owners: Corporation tax directly affects how much profit you keep to reinvest in growth, pay yourself dividends, or build a cash reserve. Understanding your effective rate helps you forecast tax bills accurately, time large purchases to maximise capital allowances, and decide whether to retain profits or extract them as dividends. With the main rate rising to 25% for profitable companies, proper planning around salary, dividends, and pension contributions becomes essential to minimise your overall tax burden.</p>`,
  },
  "personal-allowance": {
    slug: "personal-allowance",
    term: "Personal Allowance",
    category: "Tax",
    primary_kw: "UK personal allowance",
    body: `<p>Your Personal Allowance is the amount of income you can earn each tax year before you start paying Income Tax. For the 2025/26 tax year, the standard UK personal allowance is £12,570, frozen at this level until April 2028.</p>

<p>Your Personal Allowance applies to all your taxable income combined: salary from your limited company, dividends from your business, and any other earnings. This means you can structure your director's remuneration to use the full £12,570 allowance tax-efficiently. A common approach is to pay yourself a salary up to this threshold, which avoids Income Tax and National Insurance contributions (provided it stays below the primary threshold of £242 per week).</p>

<p>However, the Personal Allowance reduces if your adjusted net income exceeds £100,000. For every £2 you earn above £100,000, your allowance drops by £1. So if your total income reaches £125,140, your Personal Allowance is completely removed. This creates an effective marginal tax rate of 60% on income between £100,000 and £125,140, because you lose the allowance and pay higher-rate tax simultaneously. Many business owners in this bracket consider pension contributions or charitable donations to reduce adjusted net income and restore some or all of their allowance.</p>

<p>Your Personal Allowance is separate from the Dividend Allowance (£500 for 2025/26) and the Capital Gains Tax annual exempt amount (£3,000). It applies to earnings, rental income, and most other income types, but not to savings interest within your Personal Savings Allowance (£1,000 for basic-rate taxpayers, £500 for higher-rate).</p>

<p>If you are married or in a civil partnership, and one partner earns less than their Personal Allowance, you may be able to transfer up to £1,260 of unused allowance to the higher-earning partner via the Marriage Allowance. This is worth up to £252 in tax relief per year.</p>

<p><strong>When this matters for UK business owners</strong>: Your Personal Allowance directly affects how much tax you pay on director salary and dividends. If your total income approaches £100,000, the allowance taper creates a steep tax trap that makes pension contributions or profit extraction planning essential. Review your projected income each year to avoid losing the allowance unnecessarily.</p>`,
  },
  "dividend-allowance": {
    slug: "dividend-allowance",
    term: "Dividend Allowance",
    category: "Tax",
    primary_kw: "UK dividend allowance",
    body: `<p>The UK dividend allowance is the amount of dividend income you can receive each tax year without paying any tax on it, currently set at £500 for 2025/26.</p>

<p>For limited company directors and contractors operating through their own company, dividends are typically the most tax-efficient way to extract profits from a business. The dividend allowance sits on top of your personal allowance (£12,570 for 2025/26), meaning you can receive up to £13,070 in total income before any tax becomes due, provided all of that income is dividends.</p>

<p>Once your dividend income exceeds the £500 allowance, the rate of tax you pay depends on your total income and which Income Tax band you fall into. For 2025/26, the rates are:</p>

<ul>
<li><strong>Basic rate taxpayers</strong> (income up to £50,270): 8.75% on dividends above the allowance</li>
<li><strong>Higher rate taxpayers</strong> (income between £50,271 and £125,140): 33.75%</li>
<li><strong>Additional rate taxpayers</strong> (income over £125,140): 39.35%</li>
</ul>

<p>It is important to understand that the dividend allowance is not a tax-free allowance in the same way as the personal allowance. It is a nil-rate band, meaning you still need to report dividends within this band on your Self Assessment tax return, even though no tax is due. If you receive dividends from your limited company, you must declare them, even if they fall within the £500 allowance.</p>

<p>The allowance has been reduced significantly in recent years. It was £5,000 in 2016/17, then £2,000 from 2018/19, and dropped to £1,000 in 2023/24 and £500 in 2024/25. This means business owners who previously relied on the allowance to extract tax-free dividends now need to plan more carefully. For example, if you take £10,000 in dividends and have no other income, you would use your personal allowance (£12,570) and dividend allowance (£500) to shelter the first £13,070, leaving no tax to pay. But if you also have a salary of £12,570 from your company, your dividend allowance would be the only tax-free shield on your dividend income.</p>

<p><strong>When this matters for UK business owners</strong>: The dividend allowance directly affects how much profit you can extract from your company tax-free each year. With the allowance now at £500, you need to factor dividend tax into your overall remuneration planning, especially if you pay yourself a small salary and take the rest as dividends. It also influences decisions about timing dividend payments and whether to retain profits in the company for future years.</p>`,
  },
  "flat-rate-vat": {
    slug: "flat-rate-vat",
    term: "Flat Rate VAT Scheme",
    category: "VAT",
    primary_kw: "what is flat rate VAT",
    body: `<p>The Flat Rate VAT Scheme is a simplified VAT accounting method that lets eligible businesses pay a fixed percentage of their VAT-inclusive turnover to HMRC, instead of calculating the difference between output VAT charged to customers and input VAT claimed on purchases.</p>

<p>For many UK businesses, this scheme can reduce administrative burden and potentially increase profit margins. Under the scheme, you charge your clients the standard 20% VAT on invoices, but you pay HMRC a lower flat rate percentage based on your business sector. For most service businesses, the relevant flat rate is 14.5% (for limited cost businesses, it is 16.5%). You calculate the VAT due as 14.5% of your total VAT-inclusive turnover, then keep the difference between what you charged clients (20%) and what you pay HMRC.</p>

<p>For example, if your business invoices £100,000 plus £20,000 VAT, your VAT-inclusive turnover is £120,000. You pay HMRC 14.5% of £120,000 = £17,400, keeping £2,600 as extra profit. This works well if your business has low VAT-inclusive purchases (under 2% of turnover or under £1,000 per year) because you cannot reclaim input VAT on most purchases under the scheme.</p>

<p>Key points for UK business owners:</p>

<ul>
<li><strong>Eligibility:</strong> Your expected VAT-inclusive turnover must be £150,000 or less in the next 12 months to join. You must leave the scheme once turnover exceeds £230,000 in a year.</li>
<li><strong>Limited cost business test:</strong> If your VAT-inclusive spending on goods (not services) is less than 2% of turnover or less than £1,000 per year, you must use the 16.5% rate, which makes the scheme less beneficial.</li>
<li><strong>First year discount:</strong> Newly VAT-registered businesses get a 1% reduction on their flat rate for the first 12 months (so 13.5% for most service businesses).</li>
<li><strong>Capital assets:</strong> You can still reclaim VAT on single capital asset purchases over £2,000 including VAT.</li>
</ul>

<p>When this matters for UK business owners: The Flat Rate VAT Scheme is most valuable for businesses with low overheads and minimal purchases, such as consultants, freelancers, and limited company directors with few direct costs, where the difference between 20% charged and 14.5% paid creates a genuine profit boost. It also saves time on bookkeeping because you do not need to track every input VAT receipt. However, if your business spends heavily on subcontractors, software, or equipment, the standard VAT scheme may be more profitable because you can reclaim input VAT on those costs. Review your purchase patterns annually to decide which scheme suits you best.</p>`,
  },
  "vat-threshold": {
    slug: "vat-threshold",
    term: "VAT Registration Threshold",
    category: "VAT",
    primary_kw: "UK VAT threshold",
    body: `<p>The VAT registration threshold is the maximum taxable turnover a business can achieve in a rolling 12-month period before it must compulsorily register for Value Added Tax with HM Revenue & Customs. For UK business owners, this means the moment your cumulative sales to clients (excluding VAT) exceed £90,000 in any continuous 12-month window, you are legally required to register for VAT, charge 20% on most invoices, and submit quarterly returns.</p>

<p>The £90,000 threshold has been frozen since April 2024 and applies to the standard rate scheme. You must monitor your actual turnover, not your projected or invoiced amounts. If you expect to exceed £90,000 in the next 30 days alone, you must register immediately. Otherwise, you have 30 days from the end of the month in which you breached the threshold. For example, if your consultancy's turnover hits £91,000 on 15 March, you must notify HMRC by 30 April and receive a VAT registration effective date of 1 April (or earlier if you choose).</p>

<p>Many limited company directors and sole traders deliberately stay below £90,000 to avoid the administrative burden and the need to add 20% to client fees. However, crossing the threshold can be advantageous if your clients are VAT-registered businesses that can reclaim the VAT you charge. In that case, the extra 20% is invisible to them, and you can reclaim VAT on your own costs (software, subcontractors, equipment). If most clients are consumers or small businesses that cannot reclaim VAT, staying below the threshold may be better for pricing competitiveness.</p>

<p>You can voluntarily register for VAT before hitting £90,000, which some retailers, software companies, and food manufacturers do to appear more established or to reclaim input VAT on significant purchases. Once registered, you must remain in the scheme for at least 12 months, even if your turnover subsequently drops below the deregistration threshold (£88,000 from April 2024).</p>

<p>When this matters for UK business owners: The £90,000 UK VAT threshold directly affects your pricing strategy, cash flow, and client relationships. Hitting it unexpectedly can force you to absorb the 20% cost or renegotiate contracts. Plan your growth trajectory and decide whether to stay below, register voluntarily, or embrace VAT as a normal part of scaling your business.</p>`,
  },
  "national-insurance": {
    slug: "national-insurance",
    term: "National Insurance Contributions (NI)",
    category: "Tax",
    primary_kw: "UK national insurance explained",
    body: `<p>National Insurance Contributions (NI) are payments made by employees, employers, and the self-employed to fund state benefits, including the State Pension, NHS, and statutory payments like sick pay and maternity leave.</p>

<p>For UK businesses, NI is a significant employment cost that directly impacts profit margins and pricing strategy. As an employer, you must pay <strong>Class 1 Secondary NI</strong> on each employee's earnings above the secondary threshold (£9,100 per year for 2025/26). The rate is 13.8% on earnings above this threshold, with no upper limit. This means a salaried employee earning £40,000 costs your business an extra £4,258.20 in employer NI alone.</p>

<p>Your employees also pay <strong>Class 1 Primary NI</strong> at 8% on earnings between the primary threshold (£12,570) and the upper earnings limit (£50,270), then 2% on anything above that. As an employer, you must deduct this through PAYE and report it to HMRC each month via RTI (Real Time Information).</p>

<p>If you operate as a sole trader or through a limited company, your own NI position differs. As a sole trader, you pay <strong>Class 2 NI</strong> at £3.45 per week (2025/26) if your profits exceed £6,725, and <strong>Class 4 NI</strong> at 6% on profits between £12,570 and £50,270, then 2% above that. As a limited company director, you typically pay yourself a salary up to the secondary threshold (£9,100) to avoid employer NI, then take the rest as dividends. This is a common tax planning strategy, but be aware that dividends do not count towards NI contributions, so you may miss out on certain state benefits.</p>

<p>For businesses using contractors or freelancers, be careful with <strong>IR35</strong> rules. If HMRC determines a contractor is effectively an employee, you become liable for their employer NI contributions plus penalties. Always check the employment status of your workers.</p>

<p>When this matters for UK business owners: NI is your second biggest employment cost after salaries, so structuring pay efficiently (salary up to the NI threshold, dividends above) can save thousands each year. It also affects your pricing: if you charge clients £100 per hour, roughly £13.80 of that goes to employer NI before you see any profit. Always factor NI into your project quotes and cash flow forecasts.</p>`,
  },
  "paye": {
    slug: "paye",
    term: "PAYE (Pay As You Earn)",
    category: "Tax",
    primary_kw: "what is PAYE",
    body: `<p>PAYE (Pay As You Earn) is the system HM Revenue & Customs uses to collect Income Tax and National Insurance contributions directly from employees' wages or salaries before they receive them. For UK business owners, PAYE is the mechanism you must operate whenever you have employees, including yourself if you take a salary from your limited company. Under PAYE, you are legally responsible for deducting the correct tax and NI from each employee's pay, reporting those deductions to HMRC in real time, and paying the amounts over to HMRC monthly or quarterly.</p>

<p>When you hire your first employee or pay yourself a salary as a director, you must register as an employer with HMRC and set up a payroll system. Each time you run payroll, you calculate the employee's gross pay, then deduct Income Tax using the tax code HMRC provides (usually based on the personal allowance of £12,570 for 2025/26). You also deduct employee National Insurance at 8% on earnings between £242 and £967 per week, and 2% on anything above £967. As the employer, you must also pay employer National Insurance at 15% on earnings above £175 per week (the secondary threshold). These deductions are reported to HMRC through Real Time Information (RTI) submissions on or before each payday.</p>

<p>For limited company directors and small business owners, PAYE is particularly important because you cannot simply pay yourself dividends and ignore salary. A small salary (up to the NI threshold) can be tax-efficient because it counts as a deductible business expense and builds your state pension entitlement, while dividends take the bulk of your income. However, if you have other employees, you must operate PAYE correctly for them too, including contractors who are deemed employees under IR35 rules. The penalties for failing to operate PAYE correctly can be severe, including fines and HMRC investigations.</p>

<p>When this matters for UK business owners: PAYE is non-negotiable from the moment you have any employee, including yourself as a director taking a salary. Getting it wrong can lead to penalties, interest on unpaid tax, and reputational damage with HMRC. If you use an accountant or payroll software, ensure they handle RTI submissions and payment deadlines (usually 22nd of the following month for electronic payments). For most limited company directors, a small salary of around £9,100 per year (to avoid employee NI) combined with dividends is the standard tax-efficient approach, but always check your specific circumstances with a qualified accountant.</p>`,
  },
  "p11d": {
    slug: "p11d",
    term: "P11D (Benefits in Kind Form)",
    category: "Compliance",
    primary_kw: "what is a P11D",
    body: `<p>A P11D is the annual HMRC form that UK limited companies must use to report any non-cash benefits and expenses provided to directors or employees, such as private health insurance, company cars, or gym memberships.</p>

<p>For business owners, the P11D process is a key compliance task that runs alongside payroll. If you provide any benefits to yourself or your staff beyond salary and dividends, you must report them on a P11D form for each employee by 6 July following the end of the tax year. The most common benefits for company directors include private medical insurance, company cars with personal use, and interest-free loans over £10,000. Even if you are the sole director and only employee, you still need to submit a P11D for yourself if you receive any reportable benefits.</p>

<p>The form captures the cash equivalent value of each benefit, which HMRC uses to calculate the employee's tax liability. You must also pay Class 1A National Insurance on the value of most benefits at 13.8%, due by 19 July (or 22 July if paying electronically). For example, if you provide a company car with a taxable value of £8,000, the company pays £1,104 in Class 1A NIC, and you pay income tax on that £8,000 at your marginal rate. Some benefits, like pension contributions and workplace childcare, are exempt from reporting.</p>

<p>For 2025/26, the key figures to remember are: the £10,000 threshold for reporting beneficial loans, the £500 annual limit for trivial benefits (like a birthday gift), and the specific advisory fuel rates for company cars. If you fail to submit P11Ds on time, HMRC charges penalties starting at £100 per 50 employees per month for late returns.</p>

<p>Many company directors choose to avoid P11D reporting altogether by using a "payrolling" arrangement, where benefits are taxed through payroll in real time. This removes the need for a separate P11D submission but requires you to register with HMRC before the start of the tax year.</p>

<p><strong>When this matters for UK business owners</strong>: You need to understand what a P11D is and whether you are providing any reportable benefits to yourself or your team, because failing to submit accurate returns by the 6 July deadline can trigger penalties, interest, and HMRC compliance checks that disrupt your company's cash flow and administrative time.</p>`,
  },
  "sa100": {
    slug: "sa100",
    term: "SA100 (Self Assessment Tax Return)",
    category: "Compliance",
    primary_kw: "what is SA100",
    body: `<p>The SA100 is the standard Self Assessment tax return form used by HM Revenue & Customs (HMRC) to collect income tax and National Insurance contributions from individuals, sole traders, and partners in the UK.</p>

<p>For UK business owners, the SA100 is the default tax return you must file if HMRC asks you to complete a Self Assessment. This typically applies if you operate as a sole trader, have untaxed income from dividends or savings, earn over £2,500 from renting property, or have capital gains to report. The form covers the tax year ending 5 April, and the filing deadline for paper returns is 31 October, while online submissions must reach HMRC by 31 January following the end of the tax year.</p>

<p>The SA100 is a multi-page document divided into sections. Key pages include:</p>

<ul>
<li><strong>Page 1 (Personal details)</strong> – your name, address, National Insurance number, and contact information.</li>
<li><strong>Page 2 (Employment)</strong> – income from PAYE employment, including your P60 or P45 figures.</li>
<li><strong>Page 3 (Self-employment)</strong> – your sole trader profit or loss, calculated from your business accounts. This is where you report trading income if you are not limited by shares.</li>
<li><strong>Page 4 (Dividends and savings)</strong> – dividend income over the £500 allowance (2025/26) and interest from savings accounts.</li>
<li><strong>Page 5 (Capital gains)</strong> – gains from selling assets like shares or property, using the annual exempt amount (£3,000 for 2025/26).</li>
<li><strong>Page 6 (Tax reliefs)</strong> – pension contributions, charitable donations, and other allowable deductions.</li>
</ul>

<p>The SA100 is not used for limited companies. If you trade through a limited company, you file a CT600 corporation tax return instead. However, if you take dividends from your company as a director, you still need an SA100 to report that dividend income personally.</p>

<p>HMRC calculates your tax liability based on the figures you enter. For 2025/26, the personal allowance is £12,570. Income above that is taxed at 20% (basic rate), 40% (higher rate), or 45% (additional rate). Dividends are taxed at 8.75%, 33.75%, or 39.35% depending on your tax band. Capital gains are taxed at 18% (residential property) or 24% (other assets) for higher rate taxpayers.</p>

<p>When this matters for UK business owners: Filing the SA100 correctly ensures you pay the right amount of tax and avoid penalties. Late filing incurs a £100 automatic fine, with escalating charges after three months. If you are a sole trader, the SA100 is your primary reporting tool. If you run a limited company, you still need it for personal dividend and capital gains reporting. Getting it right saves you money and stress.</p>`,
  },
  "ct600": {
    slug: "ct600",
    term: "CT600 (Corporation Tax Return)",
    category: "Compliance",
    primary_kw: "what is CT600",
    body: `<p>The CT600 is the official HM Revenue & Customs form that limited companies must file to report their profits and calculate the corporation tax they owe for each accounting period.</p>

<p>For limited company directors and shareholders, the CT600 is your annual tax return to HMRC. It must be submitted online within 12 months of the end of your company's accounting period, though any tax due must be paid within 9 months and 1 day of that period end. The form captures your company's turnover, allowable expenses, capital allowances, and any reliefs or claims, then applies the correct corporation tax rate to work out your final liability.</p>

<p>In 2025/26, the rate depends on your company's profits. If your company's taxable profits are £50,000 or less, you pay the small profits rate of 19%. Between £50,000 and £250,000, marginal relief gradually increases the effective rate. Above £250,000, the main rate of 25% applies. For many owner-managed businesses, especially those drawing a modest salary and taking dividends, profits often fall within the 19% band, making corporation tax relatively straightforward.</p>

<p>The CT600 includes supplementary pages if your company claims R&D tax credits, has complex group structures, or makes certain elections. Most limited companies will file the standard CT600 with no extra schedules. You must also submit your company's statutory accounts and a corporation tax computation alongside the return. HMRC uses the CT600 to check your figures against your filed accounts, so consistency is essential.</p>

<p>Common mistakes include missing the filing deadline, which triggers an automatic £100 penalty (or more for repeated delays), and incorrectly calculating marginal relief if profits hover near the £50,000 or £250,000 thresholds. If your company's profits are close to these boundaries, it pays to plan ahead, for example, by making pension contributions or capital purchases to reduce taxable profits.</p>

<p>From 6 April 2026, the main rate of corporation tax remains at 25%, but the small profits rate rises to 19% (it stays at 19% for now). The CT600 itself does not change format, but the rates applied to your profits will shift.</p>

<p><strong>When this matters for UK business owners</strong>: You must file a CT600 every year your limited company trades, even if you made no profit or were dormant. Missing the deadline costs you money and HMRC attention. Understanding what is CT600 and how it interacts with your dividend strategy, salary, and allowable expenses helps you minimise tax legally and avoid penalties.</p>`,
  },
  "cis": {
    slug: "cis",
    term: "CIS (Construction Industry Scheme)",
    category: "Compliance",
    primary_kw: "what is CIS",
    body: `<p>The Construction Industry Scheme (CIS) is a UK tax deduction system requiring contractors to deduct money from subcontractors' payments and pass it directly to HMRC, effectively acting as a withholding tax for construction work.</p>

<p>For UK businesses that engage subcontractors for construction work, CIS fundamentally changes how you handle payroll and payments. If your limited company, partnership, or sole trader business hires subcontractors for construction work (including labour-only contracts, repairs, or site preparation), you are likely a deemed contractor under CIS rules. This means you must register with HMRC for CIS, verify every subcontractor before payment, deduct the correct tax rate, and submit monthly CIS returns.</p>

<p>The deduction rates for 2025/26 are: 20% for registered subcontractors who can provide their Unique Taxpayer Reference (UTR) and National Insurance number, and 30% for unregistered subcontractors who cannot verify their status. Gross payment status (where no deduction is made) is available only to subcontractors meeting strict turnover and compliance tests. You must issue a CIS payment statement to each subcontractor within 14 days of the tax month end.</p>

<p>Key compliance requirements for UK businesses include: registering your business for CIS online or by phone, verifying each subcontractor's status before their first payment (and annually thereafter), deducting the correct amount from each payment (excluding VAT), filing monthly CIS returns by the 14th of the following month, and paying the deducted amounts to HMRC by the 22nd (19th for electronic payments). Failure to register or submit returns on time triggers penalties starting at £100 per 50 subcontractors per month.</p>

<p>CIS interacts directly with your payroll processes. If you operate a PAYE scheme for construction workers, CIS deductions do not apply to employees, only to subcontractors. You must also account for apprenticeship levy (0.5% of pay bills over £3 million) and off-payroll working rules (IR35) for limited company contractors.</p>

<p>When this matters for UK business owners: If you engage any construction workers, labourers, or tradespeople as subcontractors, you must register for CIS immediately or face penalties from HMRC for non-compliance. Getting CIS right protects your business from tax liabilities, keeps subcontractors compliant, and avoids costly HMRC investigations.</p>`,
  },
  "eis-seis": {
    slug: "eis-seis",
    term: "EIS and SEIS (Investment Tax Reliefs)",
    category: "Tax",
    primary_kw: "EIS SEIS explained",
    body: `<p>The Enterprise Investment Scheme (EIS) and Seed Enterprise Investment Scheme (SEIS) are UK government tax reliefs designed to encourage individuals to invest in early-stage, unquoted companies by offering significant income tax and capital gains tax reductions.</p>

<p>For UK business owners, EIS and SEIS are powerful tools for raising external investment while offering investors a highly tax-efficient proposition. Under SEIS, which targets very early-stage startups, an investor can receive 50% income tax relief on investments of up to £100,000 per tax year (2025/26). For example, if an investor puts £20,000 into your SEIS-eligible company, they reduce their income tax bill by £10,000. Additionally, any gain on the sale of SEIS shares after three years is exempt from capital gains tax, and investors can defer other capital gains by reinvesting them into SEIS shares.</p>

<p>EIS applies to slightly more established companies and offers 30% income tax relief on investments of up to £1,000,000 per tax year (or £2,000,000 for knowledge-intensive companies). Like SEIS, EIS shares held for at least three years are free from capital gains tax on disposal. Both schemes also provide loss relief: if the company fails, investors can claim relief against income or capital gains at their marginal rate, reducing their effective risk.</p>

<p>To qualify, your company must meet several conditions. It must be a UK-based, unquoted trading company (not, for example, a property or financial services business). It cannot have more than £15 million in gross assets for EIS or £200,000 for SEIS. The shares must be newly issued, not listed on a recognised stock exchange, and the company must use the funds for a qualifying trade within two years. Importantly, you cannot be a "connected person" (e.g., a director or employee) to claim the income tax relief, though you can invest as a non-connected individual.</p>

<p>The key advantage is that EIS and SEIS make your company far more attractive to angel investors and venture capital trusts. They effectively reduce the investor's risk while giving you access to growth capital without immediate dilution of control, as the reliefs are tied to the investor, not the company.</p>

<p><strong>When this matters for UK business owners</strong>: EIS and SEIS matter most when you are raising external equity funding for the first time, typically in the seed or early growth stage. They are essential if you want to attract sophisticated investors who demand tax-efficient structures, and they can significantly lower the cost of capital for your company's expansion.</p>`,
  },
  "capital-gains-tax": {
    slug: "capital-gains-tax",
    term: "Capital Gains Tax (CGT)",
    category: "Tax",
    primary_kw: "UK capital gains tax",
    body: `<p>Capital Gains Tax (CGT) is a tax on the profit you make when you sell or dispose of an asset that has increased in value, not on the total sale proceeds. For UK business owners, CGT typically applies when you sell company shares, business assets (like goodwill or equipment), or personal investments such as a second property. The key figure is the gain: your sale price minus what you originally paid for the asset, less any allowable costs like legal fees or improvements.</p>

<p>The most common CGT event for limited company directors and shareholders is selling their company shares. If you qualify for Business Asset Disposal Relief (formerly Entrepreneurs' Relief), you pay a reduced rate of 14% on gains up to your lifetime limit of £1 million for the 2025/26 tax year. This rate rises to 18% from 6 April 2026, so if you are considering a sale, timing matters. Without relief, gains from selling company shares are taxed at 20% (for higher-rate taxpayers) or 10% (for basic-rate taxpayers, to the extent the gain falls within the basic-rate band).</p>

<p>You also have an annual exempt amount: for 2025/26, the first £3,000 of gains in a tax year are tax-free. This is down from £6,000 in 2023/24, so it is now much easier to exceed. If you sell business equipment, a client list, or other chargeable assets, any gain above that allowance is taxable. Losses can be offset against gains in the same year or carried forward, but you must report them to HMRC within four years of the end of the tax year.</p>

<p>For business owners who hold personal assets like a buy-to-let property or shares in other companies, the residential property rate is 18% for basic-rate taxpayers and 24% for higher-rate taxpayers (2025/26). This is separate from your trading assets. You must report and pay CGT within 60 days of completing a property sale using HMRC's real-time service.</p>

<p><strong>When this matters for UK business owners</strong>: When you sell your company, transfer shares, or dispose of significant business assets, CGT planning can save tens of thousands. The reduced BADR rate, the timing of the rate rise in April 2026, and your annual allowance all directly affect your net proceeds. Always calculate your gain carefully and consider professional advice before any sale.</p>`,
  },
  "holding-company": {
    slug: "holding-company",
    term: "Holding Company",
    category: "Structure",
    primary_kw: "what is a holding company",
    body: `<p>A holding company is a parent entity that owns a controlling interest in one or more subsidiary companies but typically does not itself trade, manufacture, or provide services to customers. For UK business owners, a holding company structure means you create a separate limited company that owns the shares of your trading business (the operating company), allowing you to separate ownership and control from day-to-day operations.</p>

<p>In practice, you would incorporate two companies: the holding company (often with "Holdings" or "Group" in its name) and the trading company. The holding company owns 100% of the shares in the trading company. The trading company carries out client work, employs staff, and generates revenue. The holding company receives dividends from the trading company's profits, holds assets like intellectual property or cash reserves, and can make strategic decisions without being exposed to the trading company's liabilities.</p>

<p>For limited company directors and business owners, the main advantage is tax efficiency and asset protection. When you sell the trading company, you can potentially claim Business Asset Disposal Relief (BADR) at 14% in 2025/26 (rising to 18% from 6 April 2026) on the sale of shares in the holding company, rather than paying higher rates on a direct sale. The holding company can also receive dividends from the trading company tax-free (since both are UK companies), and you can extract profits later through dividends or share buybacks. Additionally, the holding company can accumulate retained profits without triggering personal tax until you distribute them.</p>

<p>There are practical considerations. You must file separate accounts for each company and comply with Companies House requirements for both entities. The holding company needs at least one director (often you) and a registered office. You should also ensure the holding company has substance: it should hold board meetings, make strategic decisions, and maintain its own bank account, to avoid HMRC challenging the structure as a tax avoidance arrangement.</p>

<p><strong>When this matters for UK business owners</strong>: If you plan to scale, exit, or protect personal assets, a holding company structure gives you flexibility to sell the trading company while retaining the holding company's cash and assets, and to benefit from lower capital gains tax rates on disposal. It is especially relevant if you expect to sell within the next few years or want to separate your business's trading risk from your accumulated wealth.</p>`,
  },
  "spv": {
    slug: "spv",
    term: "SPV (Special Purpose Vehicle)",
    category: "Structure",
    primary_kw: "what is an SPV",
    body: `<p>An SPV (Special Purpose Vehicle) is a separate legal entity, typically a limited company, created solely to hold specific assets or undertake a particular project, isolating financial risk from the parent company or individual.</p>

<p>For UK business owners, an SPV is most commonly used when selling a company. Instead of selling the shares of your trading company directly, you sell the assets of the business into a newly formed SPV, which a buyer then purchases. This structure can offer significant tax advantages, particularly regarding Business Asset Disposal Relief (BADR). By using an SPV, you may qualify for BADR on the sale, which taxes gains at 14% in 2025/26 (rising to 18% from 6 April 2026), rather than the higher rates that could apply to a straightforward share sale. The SPV must be set up before the sale negotiations begin to satisfy HMRC's anti-avoidance rules.</p>

<p>Another use is for property investment. If your company has surplus cash, you might transfer it to an SPV to buy commercial premises. This keeps the property asset separate from the trading company, protecting it from business creditors and simplifying any future sale of the company itself. The SPV would pay corporation tax on rental income at 19% (small profits rate) or 25% (main rate), depending on its profits.</p>

<p>Key practical points for UK business owners:</p>

<ul>
<li><strong>Cost and admin:</strong> An SPV requires its own bank account, annual accounts, and Companies House filings. Expect setup costs of around £100-£300 and ongoing compliance costs of £500-£1,000 per year.</li>
<li><strong>Funding:</strong> The SPV must be capitalised properly. HMRC may challenge it as a sham if it lacks economic substance or is underfunded.</li>
<li><strong>VAT:</strong> If the SPV's taxable turnover exceeds £90,000 (the VAT threshold from April 2024), it must register for VAT separately from your main company.</li>
<li><strong>Dividend tax:</strong> If the SPV pays dividends to you, the personal dividend allowance is £500 for 2025/26, with tax rates of 8.75% (basic rate), 33.75% (higher rate), or 39.35% (additional rate).</li>
</ul>

<p>When this matters for UK business owners: An SPV is most relevant when you are planning to sell your company, want to ring-fence property or high-risk contracts, or need to isolate a specific project from your main trading company's liabilities. Always take professional advice before setting one up, as HMRC scrutinises SPVs closely for tax avoidance.</p>`,
  },
  "ebitda": {
    slug: "ebitda",
    term: "EBITDA",
    category: "Finance",
    primary_kw: "what is EBITDA",
    body: `<p>EBITDA stands for Earnings Before Interest, Taxes, Depreciation, and Amortisation, and it is a financial metric that measures a business's operating profitability by stripping out non-cash charges and financing decisions.</p>

<p>For UK business owners, EBITDA is the closest you get to seeing how much cash your core operations generate before you pay the bank, the taxman, or account for assets you bought years ago. It is calculated by taking your net profit and adding back interest, tax, depreciation, and amortisation. This gives you a cleaner view of your company's trading performance, separate from how you finance growth or structure your tax affairs.</p>

<p>Depreciation and amortisation are particularly relevant for limited companies and partnerships. You might have spent £50,000 on laptops, software licences, or office fit-outs. Those costs are spread over several years on your profit and loss account, but the cash left your bank account when you bought them. Adding them back in EBITDA shows the underlying earnings power of your client work, product sales, or retainers, not the accounting treatment of past purchases.</p>

<p>EBITDA is widely used when selling a business. Buyers often value companies on a multiple of EBITDA, typically 3x to 6x for a well-run professional services firm or product business. For example, if your EBITDA is £400,000 and the multiple is 4.5, your business might be valued at £1.8 million. This makes EBITDA a critical number to track if you plan an exit. It also influences how much you can borrow: lenders look at EBITDA to assess whether your company can service debt repayments.</p>

<p>Be aware that EBITDA is not a regulated metric under UK GAAP or IFRS. Some business owners inflate it by adding back one-off costs that are really part of normal trading, like redundancy pay or rebranding expenses. A clean, consistent EBITDA calculation is more credible to buyers and investors.</p>

<p>When this matters for UK business owners: EBITDA is the number that buyers, investors, and lenders use to value your company and decide how much to lend you. Track it monthly, keep it clean of add-backs, and understand what drives it if you plan to sell or raise finance.</p>`,
  },
  "gross-margin": {
    slug: "gross-margin",
    term: "Gross Margin",
    category: "Finance",
    primary_kw: "what is gross margin",
    body: `<p>Gross margin is the percentage of revenue that remains after deducting the direct costs of delivering your services, showing how efficiently your business turns sales into profit.</p>

<p>For limited company directors and business owners, gross margin is calculated as (revenue minus cost of goods sold) divided by revenue, multiplied by 100. In a service business, cost of goods sold typically includes the salaries and contractor fees of the team directly working on client projects, plus any software or materials used exclusively for those projects. It does not include overheads like rent, marketing, or admin salaries.</p>

<p>A healthy gross margin for a UK service business usually falls between 40% and 60%. If your margin is below 30%, you are likely undercharging, over-servicing, or carrying too many non-billable hours. Above 70% is rare for service businesses and may indicate you are not investing enough in delivery quality.</p>

<p>To calculate your gross margin accurately, you need to track time and costs per project. For example, if a client pays you £10,000 for a project, and your direct team costs (salaries, NI, pension, and software) total £4,500, your gross profit is £5,500. Your gross margin is 55%. This figure tells you how much you have left to cover your overheads and generate profit before tax.</p>

<p>Gross margin differs from net profit margin. Net profit margin deducts all operating expenses, including rent, utilities, marketing, and your own salary. Gross margin focuses purely on the efficiency of your service delivery. Improving gross margin often means raising prices, reducing project scope creep, or increasing team utilisation rates.</p>

<p>For UK businesses, the corporation tax rate (19% for profits under £50,000, 25% for profits over £250,000) applies to your net profit, not your gross margin. But a strong gross margin gives you the buffer to absorb tax liabilities, pay dividends (taxed at 8.75% to 39.35% depending on your bracket), and reinvest in growth.</p>

<p><strong>When this matters for UK business owners</strong></p>
<p>Gross margin is the single most important metric for pricing decisions, profitability analysis, and investor conversations. If you are raising prices, hiring new team members, or considering a sale of your business, gross margin tells you whether your core service model is sustainable. Track it monthly, not annually, and benchmark against the 40-60% target range for UK service businesses.</p>`,
  },
  "utilisation-rate": {
    slug: "utilisation-rate",
    term: "Utilisation Rate",
    category: "Finance",
    primary_kw: "what is agency utilisation rate",
    body: `<p>Utilisation rate measures the percentage of your team's paid working hours that are actually billed to clients, showing how efficiently you convert staff time into revenue.</p>

<p>For UK business owners, utilisation rate is one of the most important operational metrics. It tells you whether you have enough client work to keep your team busy and profitable. The calculation is straightforward: divide total billable hours by total available hours (usually excluding holidays, sick leave, and training), then multiply by 100. For example, if a consultant works 140 hours in a month and 112 are billed to clients, their utilisation rate is 80%.</p>

<p>What counts as a healthy utilisation rate depends on your business model. For service businesses with junior staff, 75-85% is typical. Senior consultants or strategists might run at 50-65% because they spend time on business development and client management. The key is to set realistic targets for each role and track them monthly.</p>

<p>Your utilisation rate directly affects profitability. If your blended team cost is £50 per hour and you charge £150 per hour, each billable hour generates £100 gross profit. A 10% drop in utilisation from 80% to 70% on a 10-person team working 1,400 hours per month means losing £14,000 in gross profit monthly. That is why business owners watch this number like hawks.</p>

<p>Common pitfalls include counting non-billable work as billable (internal meetings, proposals, admin) and failing to account for paid time off. Use a time-tracking system that separates billable from non-billable hours, and run utilisation reports weekly, not monthly. Many businesses also track "realisation rate", the percentage of billable hours you actually invoice, because write-offs and discounts eat into your effective utilisation.</p>

<p>When this matters for UK business owners: Utilisation rate determines whether you are building a profitable service business or just keeping people busy. If your utilisation drops below 65% consistently, you are losing money on every project. Use it to decide when to hire, when to restructure, and when to raise prices. It is the first number investors and buyers ask for when valuing your business.</p>`,
  },
};
